const vocabData = [
{"word": "reliable", "meaning": "可靠的；可信赖的", "pos": "adj.", "sentence": "He is a reliable friend."},
{"word": "relieve", "meaning": "减轻；解除", "pos": "v.", "sentence": "The medicine relieved his pain."},
{"word": "reluctance", "meaning": "不情愿", "pos": "n.", "sentence": "He showed reluctance to accept the offer."},
{"word": "remain", "meaning": "保持；依然；剩余", "pos": "v.", "sentence": "They remain friends."},
{"word": "remedy", "meaning": "补救；治疗法", "pos": "n.", "sentence": "Herbal remedies are popular."},
{"word": "remnant", "meaning": "残余物", "pos": "n.", "sentence": "The remnants of the ancient wall still stand."},
{"word": "renaissance", "meaning": "文艺复兴；再生", "pos": "n.", "sentence": "The Renaissance was a period of great cultural change."},
{"word": "render", "meaning": "使得；致使；给予", "pos": "v.", "sentence": "The news rendered her speechless."},
{"word": "renovate", "meaning": "翻新；修复", "pos": "v.", "sentence": "They plan to renovate the old building."},
{"word": "renowned", "meaning": "著名的", "pos": "adj.", "sentence": "He is a renowned scientist."},
{"word": "rental", "meaning": "租金", "pos": "n.", "sentence": "The rental fee is quite high."},
{"word": "repeal", "meaning": "废除；撤销", "pos": "v./n.", "sentence": "The law was repealed last year."},
{"word": "repel", "meaning": "击退；抵制", "pos": "v.", "sentence": "The army repelled the attack."},
{"word": "repetitive", "meaning": "重复的", "pos": "adj.", "sentence": "The job is repetitive and boring."},
{"word": "represent", "meaning": "代表；表示；描绘", "pos": "v.", "sentence": "He represents our company."},
{"word": "reproduce", "meaning": "繁殖；复制", "pos": "v.", "sentence": "Bacteria reproduce quickly."},
{"word": "reputation", "meaning": "名声；名誉", "pos": "n.", "sentence": "He has a good reputation."},
{"word": "request", "meaning": "请求；要求", "pos": "n./v.", "sentence": "She made a formal request."},
{"word": "requisite", "meaning": "必需品", "pos": "n.", "sentence": "Perseverance is a requisite for success."},
{"word": "resemblance", "meaning": "相似；形似", "pos": "n.", "sentence": "There is a strong resemblance between them."},
{"word": "resemble", "meaning": "像；类似", "pos": "v.", "sentence": "She resembles her mother."},
{"word": "resent", "meaning": "怨恨；愤恨", "pos": "v.", "sentence": "He resents the criticism."},
{"word": "reservation", "meaning": "预订；保留意见", "pos": "n.", "sentence": "I made a reservation for dinner."},
{"word": "reserve", "meaning": "保留；预订", "pos": "v.", "sentence": "Please reserve a table for two."},
{"word": "reservoir", "meaning": "水库；蓄水池", "pos": "n.", "sentence": "The reservoir provides water to the city."},
{"word": "reside", "meaning": "居住", "pos": "v.", "sentence": "He resides in New York."},
{"word": "resilience", "meaning": "韧性；弹力", "pos": "n.", "sentence": "Children often show great resilience."},
{"word": "resist", "meaning": "抵抗；忍耐", "pos": "v.", "sentence": "She couldn't resist the temptation."},
{"word": "resolution", "meaning": "决心；决议；分辨率", "pos": "n.", "sentence": "He made a resolution to exercise more."},
{"word": "resolve", "meaning": "解决；决定；分解", "pos": "v.", "sentence": "We need to resolve this issue."},
{"word": "resonance", "meaning": "共鸣；反响", "pos": "n.", "sentence": "The speech had great resonance."},
{"word": "resort", "meaning": "度假胜地", "pos": "n.", "sentence": "They stayed at a ski resort."},
{"word": "resource", "meaning": "资源；谋略", "pos": "n.", "sentence": "Natural resources are limited."},
{"word": "respective", "meaning": "各自的", "pos": "adj.", "sentence": "They went to their respective homes."},
{"word": "respectively", "meaning": "各自地", "pos": "adv.", "sentence": "John and Mary are 25 and 30 respectively."},
{"word": "responsibility", "meaning": "责任；职责", "pos": "n.", "sentence": "He took full responsibility."},
{"word": "restrain", "meaning": "抑制；制止", "pos": "v.", "sentence": "He tried to restrain his anger."},
{"word": "resume", "meaning": "继续；重新开始", "pos": "v./n.", "sentence": "Let's resume the meeting."},
{"word": "retain", "meaning": "保持；保留", "pos": "v.", "sentence": "He managed to retain his position."},
{"word": "retention", "meaning": "保留；记忆力", "pos": "n.", "sentence": "Employee retention is important."},
{"word": "retort", "meaning": "反驳；回嘴", "pos": "v./n.", "sentence": "She made a sharp retort."},
{"word": "retrieve", "meaning": "取回；挽回", "pos": "v.", "sentence": "He retrieved his lost wallet."},
{"word": "retrospect", "meaning": "回顾", "pos": "n./v.", "sentence": "In retrospect, it was a mistake."},
{"word": "reveal", "meaning": "揭露；显示", "pos": "v.", "sentence": "The investigation revealed the truth."},
{"word": "revenue", "meaning": "收入；税收", "pos": "n.", "sentence": "The company's revenue increased."},
{"word": "reverence", "meaning": "尊敬", "pos": "n.", "sentence": "He showed great reverence for the tradition."},
{"word": "reverse", "meaning": "相反", "pos": "adj.", "sentence": "The reverse side of the coin."},
{"word": "revive", "meaning": "复兴；苏醒", "pos": "v.", "sentence": "The patient revived after treatment."},
{"word": "revolution", "meaning": "革命；旋转", "pos": "n.", "sentence": "The revolution changed the country."},
{"word": "sacrifice", "meaning": "牺牲；祭祀", "pos": "v./n.", "sentence": "She sacrificed her career for her family."},
{"word": "safeguard", "meaning": "保护", "pos": "v.", "sentence": "We must safeguard our rights."},
{"word": "salient", "meaning": "显著的；突出的", "pos": "adj.", "sentence": "He pointed out the salient features."},
{"word": "salvage", "meaning": "抢救；打捞", "pos": "v./n.", "sentence": "They tried to salvage the ship."},
{"word": "sanction", "meaning": "制裁；批准", "pos": "n./v.", "sentence": "The UN imposed sanctions."},
{"word": "sanitary", "meaning": "卫生的", "pos": "adj.", "sentence": "Sanitary conditions are poor."},
{"word": "satire", "meaning": "讽刺", "pos": "n.", "sentence": "The play is a political satire."},
{"word": "saturate", "meaning": "浸透；使饱和", "pos": "v.", "sentence": "The market is saturated."},
{"word": "savage", "meaning": "野蛮的；凶猛的", "pos": "adj.", "sentence": "It was a savage attack."},
{"word": "scandal", "meaning": "丑闻", "pos": "n.", "sentence": "The scandal ruined his career."},
{"word": "scant", "meaning": "不足的；缺乏的", "pos": "adj.", "sentence": "There is scant evidence."},
{"word": "scarce", "meaning": "缺乏的；稀有的", "pos": "adj.", "sentence": "Food was scarce during the war."},
{"word": "scarcity", "meaning": "稀少；缺乏", "pos": "n.", "sentence": "Water scarcity is a serious problem."},
{"word": "scatter", "meaning": "散播；驱散", "pos": "v.", "sentence": "The wind scattered the leaves."},
{"word": "scenario", "meaning": "剧本；设想；方案", "pos": "n.", "sentence": "In a worst-case scenario..."},
{"word": "scenic", "meaning": "风景优美的", "pos": "adj.", "sentence": "We took the scenic route."},
{"word": "scent", "meaning": "香味；气味", "pos": "n.", "sentence": "The scent of flowers filled the air."},
{"word": "scorn", "meaning": "轻蔑；藐视", "pos": "n./v.", "sentence": "She looked at him with scorn."},
{"word": "scramble", "meaning": "攀登；争夺", "pos": "v.", "sentence": "He scrambled up the hill."},
{"word": "scrutiny", "meaning": "详细检查；监视", "pos": "n.", "sentence": "The plan is under close scrutiny."},
{"word": "sculpture", "meaning": "雕塑", "pos": "n.", "sentence": "The sculpture is on display."},
{"word": "secondary", "meaning": "次要的；中级的", "pos": "adj.", "sentence": "This is a secondary issue."},
{"word": "sector", "meaning": "部门；扇形", "pos": "n.", "sentence": "The private sector is growing."},
{"word": "secular", "meaning": "世俗的", "pos": "adj.", "sentence": "We live in a secular society."},
{"word": "secure", "meaning": "安全的；获得；保护", "pos": "adj./v.", "sentence": "The door is secure."},
{"word": "security", "meaning": "安全；证券", "pos": "n.", "sentence": "National security is a priority."},
{"word": "segment", "meaning": "切片；部分", "pos": "n.", "sentence": "The market segment is growing."},
{"word": "segregate", "meaning": "隔离；分开", "pos": "v.", "sentence": "The system used to segregate people."},
{"word": "selective", "meaning": "精选的；有选择性的", "pos": "adj.", "sentence": "The school is very selective."},
{"word": "senate", "meaning": "参议院", "pos": "n.", "sentence": "The Senate passed the bill."},
{"word": "sensation", "meaning": "感觉；轰动", "pos": "n.", "sentence": "The news caused a sensation."},
{"word": "sensible", "meaning": "明智的；感觉得到的", "pos": "adj.", "sentence": "That's a sensible suggestion."},
{"word": "sensitivity", "meaning": "敏感性；灵敏度", "pos": "n.", "sentence": "He has great sensitivity to light."},
{"word": "sentimental", "meaning": "多愁善感的", "pos": "adj.", "sentence": "She is very sentimental."},
{"word": "sequence", "meaning": "序列；先后次序", "pos": "n.", "sentence": "The events happened in sequence."},
{"word": "serene", "meaning": "安详的；晴朗的", "pos": "adj.", "sentence": "The lake was serene."},
{"word": "setback", "meaning": "挫折；退步", "pos": "n.", "sentence": "It was a major setback."},
{"word": "settlement", "meaning": "解决；定居点", "pos": "n.", "sentence": "They reached a settlement."},
{"word": "severe", "meaning": "严重的；严厉的", "pos": "adj.", "sentence": "The punishment was severe."},
{"word": "shabby", "meaning": "破旧的；卑鄙的", "pos": "adj.", "sentence": "He wore a shabby coat."},
{"word": "shallow", "meaning": "浅的；浅薄的", "pos": "adj.", "sentence": "The water is shallow here."},
{"word": "sham", "meaning": "伪装；虚假", "pos": "n./adj.", "sentence": "It was a sham election."},
{"word": "shareholder", "meaning": "股东", "pos": "n.", "sentence": "The shareholders voted."},
{"word": "shatter", "meaning": "粉碎；破灭", "pos": "v.", "sentence": "The glass shattered."},
{"word": "shear", "meaning": "剪；剥夺", "pos": "v.", "sentence": "Sheep are sheared for wool."},
{"word": "sheer", "meaning": "纯粹的；陡峭的", "pos": "adj.", "sentence": "It was sheer luck."},
{"word": "shelter", "meaning": "掩体", "pos": "n.", "sentence": "They sought shelter from the rain."},
{"word": "shield", "meaning": "盾", "pos": "n.", "sentence": "The shield protected the knight."},
{"word": "shiver", "meaning": "战栗；发抖", "pos": "v./n.", "sentence": "She shivered with cold."},
{"word": "shrewd", "meaning": "精明的；敏锐的", "pos": "adj.", "sentence": "He is a shrewd businessman."},
{"word": "shrink", "meaning": "收缩；退缩", "pos": "v.", "sentence": "The sweater shrank in the wash."},
];
