const vocabData = [
{"word": "abolish", "meaning": "废除，废止，取消", "pos": "v.", "sentence": "The law was abolished."},
{"word": "abortion", "meaning": "流产，堕胎", "pos": "n.", "sentence": "Abortion is a controversial topic."},
{"word": "abundance", "meaning": "丰富，充裕，大量", "pos": "n.", "sentence": "There is an abundance of food."},
{"word": "abundant", "meaning": "丰富的，充裕的，大量的", "pos": "adj.", "sentence": "The region has abundant resources."},
{"word": "accessory", "meaning": "附件，配件，装饰品，从犯", "pos": "n.", "sentence": "He bought a phone accessory."},
{"word": "accommodate", "meaning": "容纳，提供住宿，适应，顺应", "pos": "v.", "sentence": "The hotel can accommodate 500 guests."},
{"word": "accomplish", "meaning": "完成，实现，达到", "pos": "v.", "sentence": "She accomplished her goal."},
{"word": "accord", "meaning": "协议，条约；一致，符合", "pos": "n.", "sentence": "They signed a peace accord."},
{"word": "accountant", "meaning": "会计，会计师", "pos": "n.", "sentence": "She works as an accountant."},
{"word": "accumulate", "meaning": "积累，积聚，逐渐增加", "pos": "v.", "sentence": "He accumulated great wealth."},
{"word": "accurate", "meaning": "准确的，精确的，正确无误的", "pos": "adj.", "sentence": "The data is accurate."},
{"word": "accuse", "meaning": "指控，控告，指责，谴责", "pos": "v.", "sentence": "He was accused of theft."},
{"word": "accustomed", "meaning": "习惯的，通常的，惯常的", "pos": "adj.", "sentence": "She is accustomed to hard work."},
{"word": "achievement", "meaning": "成就，成绩，功绩", "pos": "n.", "sentence": "This is a great achievement."},
{"word": "acknowledge", "meaning": "承认，认可，答谢，确认收到", "pos": "v.", "sentence": "He acknowledged his mistake."},
{"word": "acquaint", "meaning": "使熟悉，使了解，告知", "pos": "v.", "sentence": "Let me acquaint you with the rules."},
{"word": "acquisition", "meaning": "获得，收购，习得", "pos": "n.", "sentence": "The acquisition was successful."},
{"word": "adequate", "meaning": "足够的，适当的，合格的", "pos": "adj.", "sentence": "The supply is adequate."},
{"word": "Abide by", "meaning": "遵守", "pos": "v.", "sentence": "You must abide by the rules."},
{"word": "In accordance with", "meaning": "依照、根据", "pos": "prep.", "sentence": "Act in accordance with the law."},
{"word": "On account of", "meaning": "由于、因为", "pos": "prep.", "sentence": "He stayed on account of the rain."},
{"word": "Adhere to", "meaning": "坚持", "pos": "v.", "sentence": "We must adhere to the plan."},
{"word": "badge", "meaning": "徽章；标记", "pos": "n.", "sentence": "She wore a badge."},
{"word": "baggage", "meaning": "行李", "pos": "n.", "sentence": "Check your baggage."},
{"word": "balcony", "meaning": "阳台", "pos": "n.", "sentence": "She stood on the balcony."},
{"word": "bald", "meaning": "秃头的；明显的", "pos": "adj.", "sentence": "He is going bald."},
{"word": "ballot", "meaning": "投票；投票总数；选票", "pos": "n.", "sentence": "Cast your ballot."},
{"word": "bandage", "meaning": "绷带；用绷带扎缚", "pos": "n./v.", "sentence": "Apply a bandage to the wound."},
{"word": "bankrupt", "meaning": "破产的；使破产", "pos": "adj./v.", "sentence": "The company went bankrupt."},
{"word": "barely", "meaning": "仅仅；几乎不", "pos": "adv.", "sentence": "He barely escaped."},
{"word": "bargain", "meaning": "廉价货；契约；讨价还价", "pos": "n./v.", "sentence": "It was a real bargain."},
{"word": "barrel", "meaning": "桶；枪管", "pos": "n.", "sentence": "A barrel of oil."},
{"word": "batch", "meaning": "一批；一组", "pos": "n.", "sentence": "A batch of cookies."},
{"word": "canal", "meaning": "运河；沟渠", "pos": "n.", "sentence": "The Suez Canal."},
{"word": "caption", "meaning": "标题；说明文字", "pos": "n.", "sentence": "Read the caption."},
{"word": "cargo", "meaning": "货物", "pos": "n.", "sentence": "The ship carries cargo."},
{"word": "carrier", "meaning": "搬运者；载体；航空母舰", "pos": "n.", "sentence": "An aircraft carrier."},
{"word": "catalog", "meaning": "目录；为……编目", "pos": "n./v.", "sentence": "Check the catalog."},
{"word": "catastrophe", "meaning": "大灾难", "pos": "n.", "sentence": "The flood was a catastrophe."},
{"word": "Carry out", "meaning": "贯彻；执行；实现", "pos": "v.", "sentence": "Carry out the plan."},
{"word": "Comply with", "meaning": "遵守；服从", "pos": "v.", "sentence": "Comply with the regulations."},
{"word": "Conform to", "meaning": "遵守；符合", "pos": "v.", "sentence": "Conform to the standards."},
{"word": "dash", "meaning": "冲撞；猛冲；破折号", "pos": "v./n.", "sentence": "Make a dash for it."},
{"word": "decade", "meaning": "十年", "pos": "n.", "sentence": "A decade has passed."},
{"word": "decay", "meaning": "腐烂；衰退", "pos": "v./n.", "sentence": "The fruit began to decay."},
{"word": "deceive", "meaning": "欺骗；蒙蔽", "pos": "v.", "sentence": "Don't deceive me."},
{"word": "decent", "meaning": "体面的；正派的；像样的", "pos": "adj.", "sentence": "A decent salary."},
{"word": "decline", "meaning": "下降；衰落；谢绝", "pos": "v./n.", "sentence": "The population is declining."},
{"word": "dedicate", "meaning": "奉献；题献", "pos": "v.", "sentence": "He dedicated his life to science."},
{"word": "deduce", "meaning": "推断；演绎", "pos": "v.", "sentence": "What can we deduce from this?"},
{"word": "deed", "meaning": "行为；契约", "pos": "n.", "sentence": "A good deed."},
{"word": "defect", "meaning": "缺点；瑕疵", "pos": "n.", "sentence": "A manufacturing defect."},
{"word": "defy", "meaning": "挑衅；违抗；藐视", "pos": "v.", "sentence": "Don't defy the rules."},
{"word": "delegate", "meaning": "代表；委派……为代表", "pos": "n./v.", "sentence": "A delegate to the conference."},
{"word": "deliberate", "meaning": "故意的；深思熟虑的", "pos": "adj.", "sentence": "A deliberate attempt."},
{"word": "delicate", "meaning": "精致的；脆弱的；微妙的", "pos": "adj.", "sentence": "A delicate situation."},
{"word": "democracy", "meaning": "民主；民主国家", "pos": "n.", "sentence": "A thriving democracy."},
{"word": "demolish", "meaning": "拆除；推翻；破坏", "pos": "v.", "sentence": "Demolish the old building."},
{"word": "denote", "meaning": "象征；表示", "pos": "v.", "sentence": "What does this symbol denote?"},
{"word": "denounce", "meaning": "谴责；告发", "pos": "v.", "sentence": "Denounce the crime."},
{"word": "dense", "meaning": "密集的；浓厚的", "pos": "adj.", "sentence": "A dense forest."},
{"word": "deny", "meaning": "否认；拒绝给予", "pos": "v.", "sentence": "He denied the accusation."},
{"word": "depart", "meaning": "离开；出发", "pos": "v.", "sentence": "The train departs at 8."},
{"word": "depict", "meaning": "描绘；描述", "pos": "v.", "sentence": "The painting depicts a battle."},
{"word": "deposit", "meaning": "存放；储蓄；存款；押金；沉淀物", "pos": "v./n.", "sentence": "Make a deposit."},
{"word": "deprive", "meaning": "剥夺；使丧失", "pos": "v.", "sentence": "Deprive him of his rights."},
{"word": "derive", "meaning": "起源于；获得", "pos": "v.", "sentence": "The word derives from Latin."},
{"word": "descend", "meaning": "下降；传承", "pos": "v.", "sentence": "The plane began to descend."},
{"word": "designate", "meaning": "指派；指明", "pos": "v.", "sentence": "Designate a meeting place."},
{"word": "despair", "meaning": "绝望", "pos": "n./v.", "sentence": "He was in despair."},
{"word": "desperate", "meaning": "绝望的；不顾一切的", "pos": "adj.", "sentence": "A desperate attempt."},
{"word": "despise", "meaning": "轻视；蔑视", "pos": "v.", "sentence": "I despise liars."},
{"word": "detach", "meaning": "分离；拆开", "pos": "v.", "sentence": "Detach the trailer."},
{"word": "deteriorate", "meaning": "恶化；变坏", "pos": "v.", "sentence": "His health deteriorated."},
{"word": "determine", "meaning": "决定；确定；决心", "pos": "v.", "sentence": "Determine the cause."},
{"word": "detriment", "meaning": "损害；伤害", "pos": "n.", "sentence": "To the detriment of his health."},
{"word": "devote", "meaning": "献身于；致力于", "pos": "v.", "sentence": "Devote time to study."},
{"word": "diagram", "meaning": "图表；图解", "pos": "n.", "sentence": "Draw a diagram."},
{"word": "dialect", "meaning": "方言", "pos": "n.", "sentence": "A local dialect."},
{"word": "diameter", "meaning": "直径", "pos": "n.", "sentence": "The diameter of the circle."},
{"word": "dictate", "meaning": "听写；命令", "pos": "v.", "sentence": "Dictate a letter."},
{"word": "differentiate", "meaning": "区分；区别", "pos": "v.", "sentence": "Differentiate between the two."},
{"word": "diffuse", "meaning": "扩散；传播；弥漫的", "pos": "v./adj.", "sentence": "The light diffused."},
{"word": "dignity", "meaning": "尊严；高贵", "pos": "n.", "sentence": "Maintain your dignity."},
{"word": "diligent", "meaning": "勤勉的；用功的", "pos": "adj.", "sentence": "A diligent student."},
{"word": "dilute", "meaning": "稀释；变淡", "pos": "v.", "sentence": "Dilute the solution."},
{"word": "diminish", "meaning": "减少；减弱；贬低", "pos": "v.", "sentence": "His influence diminished."},
{"word": "diplomat", "meaning": "外交官", "pos": "n.", "sentence": "A skilled diplomat."},
{"word": "discard", "meaning": "丢弃；抛弃", "pos": "v.", "sentence": "Discard the old files."},
{"word": "discern", "meaning": "辨别；识别", "pos": "v.", "sentence": "Discern the truth."},
{"word": "discharge", "meaning": "释放；排出；解雇", "pos": "v./n.", "sentence": "Discharge the patient."},
{"word": "discipline", "meaning": "纪律；学科；训练", "pos": "n./v.", "sentence": "Maintain discipline."},
{"word": "disguise", "meaning": "伪装；掩饰", "pos": "v./n.", "sentence": "Disguise yourself."},
{"word": "dismiss", "meaning": "解雇；解散；驳回", "pos": "v.", "sentence": "Dismiss the class."},
{"word": "disorder", "meaning": "混乱；失调；紊乱", "pos": "n.", "sentence": "A sleep disorder."},
{"word": "dispatch", "meaning": "派遣；发送", "pos": "v./n.", "sentence": "Dispatch a messenger."},
{"word": "dispel", "meaning": "驱散；消除", "pos": "v.", "sentence": "Dispel the rumors."},
{"word": "dispense", "meaning": "分配；分发；免除", "pos": "v.", "sentence": "Dispense medicine."},
{"word": "displace", "meaning": "取代；置换；使流离失所", "pos": "v.", "sentence": "The dam displaced many people."},
{"word": "display", "meaning": "陈列；展示", "pos": "v./n.", "sentence": "Display the results."}
];
