const vocabData = [
{"word": "numerosity", "meaning": "数量效应，数值感知", "pos": "n.", "sentence": "Presenting an installment amount rather than the full price lowers a consumer's perception of the cost. This is due to the numerosity effect."},
{"word": "shedding light on", "meaning": "阐明，揭示", "pos": "phrase", "sentence": "After realizing how much they actually owed, 1 in 4 Americans say they've regretted using BNPL, and a new study is shedding light on why these plans are so tempting."},
{"word": "tempting", "meaning": "诱人的，有吸引力的", "pos": "adj.", "sentence": "A new study is shedding light on why these plans are so tempting."},
{"word": "internalizing", "meaning": "内化", "pos": "v.", "sentence": "With these installment plans, people may not be fully internalizing the cost of a purchase when deciding whether to buy or how much to spend."},
{"word": "literacy", "meaning": "读写能力，素养", "pos": "n.", "sentence": "Professionals within esports psychology perform roles that combine high-performance coaching, clinical or counseling skills, and deep game literacy."},
{"word": "nuanced", "meaning": "细致入微的，微妙的", "pos": "adj.", "sentence": "However, a more nuanced approach is necessary when esports competitors often require those hours to train and remain competitive."},
{"word": "prioritized", "meaning": "优先考虑的", "pos": "v.", "sentence": "Gardner and his team prioritized exercise, sleep routines, and intrinsic motivation, helping the Immortals players build healthier daily structures."},
{"word": "meteoric", "meaning": "迅速的，流星般的", "pos": "adj.", "sentence": "Its meteoric rise demonstrates the internet's power to propel fringe terms into the mainstream at warp speed."},
{"word": "fringe", "meaning": "边缘的，非主流的", "pos": "adj.", "sentence": "Its meteoric rise demonstrates the internet's power to propel fringe terms into the mainstream at warp speed."},
{"word": "rebellious", "meaning": "叛逆的，反抗的", "pos": "adj.", "sentence": "For young people, the appeal lies in its irreverent or rebellious qualities while also remaining opaque to adults."},
{"word": "opaque", "meaning": "晦涩难懂的，不透明的", "pos": "adj.", "sentence": "For young people, the appeal lies in its irreverent or rebellious qualities while also remaining opaque to adults."},
{"word": "shorthand", "meaning": "简写，速记", "pos": "n.", "sentence": "That verbal shorthand persists in modern professional settings as jargon."},
{"word": "boost", "meaning": "提升，增强，促进", "pos": "v.", "sentence": "Psychology researchers are developing cognitive interventions to help adults boost their brain health rather than being affected by harmful stereotypes about aging."},
{"word": "upfront", "meaning": "预先的，事先的", "pos": "adj.", "sentence": "For older workers to overcome barriers to learning, they often need to know upfront how training will benefit them."},
{"word": "adherent", "meaning": "遵从的，坚持的", "pos": "n.", "sentence": "They were very adherent, and there was a low dropout rate."},
{"word": "jargon", "meaning": "行话，术语", "pos": "n.", "sentence": "That verbal shorthand persists in modern professional settings as jargon."},
{"word": "curriculum", "meaning": "课程", "pos": "n.", "sentence": "Garden State Esports developed the Esports Personal and Performance Improvement Curriculum (EPPIC)."},
{"word": "dearth", "meaning": "缺乏，短缺", "pos": "n.", "sentence": "There is a dearth of appropriate evidence-based practices and ethical and professional standards."},
{"word": "deliberate", "meaning": "故意的，深思熟虑的", "pos": "adj.", "sentence": "A study with Counter-Strike: Global Offensive and League of Legends players found that deliberate practice did not meaningfully predict long-term rank."},
{"word": "immortals", "meaning": "不朽者（电竞战队名）", "pos": "n.", "sentence": "In 2018, he built what he describes as the first player development department in North American professional esports for the Immortals organization."},
{"word": "leveraging", "meaning": "利用，借助", "pos": "v.", "sentence": "The rise of livestreaming platforms like Twitch, Discord, and YouTube—and the charismatic personalities of some of the athletes leveraging these platforms—has fueled this growth."},
{"word": "navigate", "meaning": "导航，应对", "pos": "v.", "sentence": "While elite players within formal organizational structures often have access to professional psychological services, non-elite players must rely on inconsistent online resources or navigate support systems on their own."},
{"word": "likened", "meaning": "比作，比拟", "pos": "v.", "sentence": "Ryan Terao, PsyD, an esports and licensed clinical psychologist, likened the power of esports and gaming to fire."},
{"word": "marginalized", "meaning": "边缘化的", "pos": "adj.", "sentence": "Strobel views esports as widening accessibility for students who may be marginalized in traditional sports, including neurodivergent youth."},
{"word": "merge", "meaning": "合并，融合", "pos": "v.", "sentence": "I've been spending outside the game to learn all these skills and merge them with my passion for the game."},
{"word": "mindset-reappraisal", "meaning": "心态重新评估", "pos": "n.", "sentence": "A mindset-reappraisal intervention that encouraged players to view stress as beneficial lowered players' anxiety."},
{"word": "mitigate", "meaning": "减轻，缓解", "pos": "v.", "sentence": "What we really need to do is track young people over their development to understand when gaming is good and when it is bad, and then how to mitigate the bad and maximize the good."},
{"word": "mound", "meaning": "投手丘（棒球）", "pos": "n.", "sentence": "This would be akin to a player committing a flagrant foul in basketball or rushing the mound in baseball."},
{"word": "movember", "meaning": "Movember（男性健康慈善机构）", "pos": "n.", "sentence": "In 2024, the global men's health charity Movember recruited esports psychology researcher Dylan Poulus, PhD."},
{"word": "multibillion-dollar", "meaning": "数十亿美元的", "pos": "adj.", "sentence": "Esports are a fast-evolving multibillion-dollar industry that draws hundreds of millions of competitive video game players worldwide."},
{"word": "navigating", "meaning": "应对，穿越", "pos": "v.", "sentence": "EPPIC addresses communication, teamwork, leadership, health and wellness, and navigating online toxicity and hate speech."},
{"word": "neurodivergent", "meaning": "神经多样性者", "pos": "n.", "sentence": "Strobel views esports as widening accessibility for students who may be marginalized in traditional sports, including neurodivergent youth."},
{"word": "normalizing", "meaning": "正常化", "pos": "v.", "sentence": "Students gained access to an athletics-based sport psychologist, nutrition programming, and twice-weekly morning workouts aimed at normalizing physical conditioning."},
{"word": "norms", "meaning": "规范，准则", "pos": "n.", "sentence": "Teams were also encouraged to develop their own norms around culture, accountability, and conflict management."},
{"word": "off-ramp", "meaning": "退出通道，出路", "pos": "n.", "sentence": "Many pros go straight from an anonymous position on a ladder to a contract, with no Little League, no college team, and no off-ramp when it ends."},
{"word": "pillars", "meaning": "支柱，核心原则", "pos": "n.", "sentence": "Poulus and colleagues convened game publishers, tournament organizers, International Olympic Committee representatives, and mental health experts to finalize nine pillars of mental health support."},
{"word": "pipeline", "meaning": "管道，人才输送渠道", "pos": "n.", "sentence": "Esports is a sport without a childhood pipeline."},
{"word": "postgame", "meaning": "赛后的", "pos": "adj.", "sentence": "He often prepares clients to expect a temporary dip in performance as they reconstruct habits around sleep, practice structure, and postgame review."},
{"word": "reckless", "meaning": "鲁莽的，轻率的", "pos": "adj.", "sentence": "Tilt can lead players to perform reckless and self-destructive actions, such as hurtling their character, unprotected, at an enemy."},
{"word": "reconceptualize", "meaning": "重新概念化", "pos": "v.", "sentence": "Getting players to reconceptualize stress as being beneficial and a challenge to overcome rather than a debilitating threat improved shooting accuracy."},
{"word": "recruited", "meaning": "招募的", "pos": "v.", "sentence": "In 2024, the global men's health charity Movember recruited esports psychology researcher Dylan Poulus, PhD."},
{"word": "relegated", "meaning": "被降级", "pos": "v.", "sentence": "As a result, neurodivergent youth in esports get to be the captain of the team versus the helper role they are often relegated to in traditional sports."},
{"word": "resembled", "meaning": "类似于", "pos": "v.", "sentence": "Researchers found 51 stressors, such as communication problems and pressures of competing before live audiences, resembled those affecting professional athletes in traditional sports."},
{"word": "rigor", "meaning": "严谨性", "pos": "n.", "sentence": "The evidence base is expanding rapidly, but it lacks the rigor necessary for evidence-based practice."},
{"word": "sanctioned", "meaning": "认可的，批准的", "pos": "adj.", "sentence": "Roose intentionally housed the program within the athletics department and adopted the NCAA's 20-hour rule for sanctioned activities."},
{"word": "scrutiny", "meaning": "审查，审视", "pos": "n.", "sentence": "Many esports players begin competing professionally in adolescence, facing intense pressure, unstable schedules, and public scrutiny while still developing emotionally and socially."},
{"word": "self-efficacy", "meaning": "自我效能感", "pos": "n.", "sentence": "However, mindset and self-efficacy are key."},
{"word": "self-sufficiency", "meaning": "自给自足", "pos": "n.", "sentence": "Teams were also encouraged to develop their own norms around culture, accountability, and conflict management, fostering self-sufficiency and leadership skills."},
{"word": "semiprofessional", "meaning": "半职业的", "pos": "adj.", "sentence": "Players often compete as teams on digital platforms through systems run by amateur, semiprofessional, or professional leagues."},
{"word": "sharpen", "meaning": "加强，提高", "pos": "v.", "sentence": "New studies on stress, tilt, practice demands, and attention will sharpen understanding of what drives performance in the digital game environment."},
{"word": "shooting", "meaning": "射击", "pos": "n.", "sentence": "Popular genres of esports include shooting games (Counter-Strike)."},
{"word": "shortfall", "meaning": "不足，缺口", "pos": "n.", "sentence": "While there are more sports psychologists and certified performance coaches entering the esports space, there is still a significant shortfall of qualified professionals."},
{"word": "stretches", "meaning": "一段时间，延伸", "pos": "n.", "sentence": "Players often practice for long stretches with minimal physical movement and irregular sleep schedules."},
{"word": "subdisciplines", "meaning": "分支学科", "pos": "n.", "sentence": "Esports psychologists come from many different subdisciplines and are working to bring evidence-based approaches to performance, mental health, and player development."},
{"word": "toxicity", "meaning": "毒性，有害性", "pos": "n.", "sentence": "EPPIC addresses communication, teamwork, leadership, health and wellness, and navigating online toxicity and hate speech."},
{"word": "transition", "meaning": "过渡，转变", "pos": "n.", "sentence": "They also incorporated transition planning, encouraging players to apply to college or complete a GED."},
{"word": "slang", "meaning": "俚语，行话", "pos": "n.", "sentence": "Slang is one of these really classic indicators of identity."},
{"word": "sheds", "meaning": "散发，流露", "pos": "v.", "sentence": "Slang sheds light on the complexity of identity formation and belonging in a fast-paced digital world."},
{"word": "Originating", "meaning": "起源于，源自", "pos": "v.", "sentence": "Originating from a somewhat obscure rap song in late 2024, it quickly gained momentum on TikTok and other social media platforms."},
{"word": "a linguistic quirk", "meaning": "语言怪癖，语言特色", "pos": "n.", "sentence": "Slang, however, is more than a linguistic quirk for people of all ages."},
{"word": "secrecy and informality shapes", "meaning": "秘密性和非正式性塑造了", "pos": "phrase", "sentence": "That early association with secrecy and informality shapes modern perceptions of slang as something outside the bounds of formal speech or writing."},
{"word": "incorporating colloquialisms", "meaning": "纳入口语表达，融入俗语", "pos": "v.", "sentence": "Contemporary slang also heavily reflects the influences of youth-driven pop culture and digital media while also incorporating colloquialisms that originated from LGBTQ+ communities."},
{"word": "illustrative users", "meaning": "示范性使用者，偶尔使用者", "pos": "n.", "sentence": "Primary users create and use slang in their everyday speech, and illustrative users adopt slang occasionally to signal authenticity to others."},
{"word": "signal authenticity", "meaning": "传递真实性，表明真实身份", "pos": "phrase", "sentence": "Primary users create and use slang in their everyday speech, and illustrative users adopt slang occasionally to signal authenticity to others."},
{"word": "social inferiority", "meaning": "社会地位低下，社会劣势", "pos": "n.", "sentence": "While slang can signal a desirable image of youthfulness or social currency, it can also carry the risk of stigma, suggesting a lack of professionalism or social inferiority."},
{"word": "leveraging neuroplasticity", "meaning": "利用神经可塑性", "pos": "v.", "sentence": "Their findings suggest that leveraging neuroplasticity at any age can increase confidence, motivation, and the desire to tackle new challenges."},
{"word": "implement", "meaning": "实施，执行，贯彻", "pos": "v.", "sentence": "Innovative, research-backed interventions that help aging adults implement new behaviors related to fitness, diet, and learning have been shown to improve and prolong cognitive health."},
{"word": "prolong", "meaning": "延长，延续", "pos": "v.", "sentence": "Innovative, research-backed interventions that help aging adults implement new behaviors related to fitness, diet, and learning have been shown to improve and prolong cognitive health."},
{"word": "internalized ageism", "meaning": "内化的年龄歧视", "pos": "n.", "sentence": "Whereas internalized ageism can lead older adults to believe that they can't learn and must give up things that are important to them, research suggests that positive age beliefs can lead to better health and a longer life."},
{"word": "demographic", "meaning": "人群，人口群体", "pos": "n.", "sentence": "But researchers hope to see communities increase access to affordable ways for this demographic to learn—both online and in-person."},
{"word": "immersed", "meaning": "沉浸的，全身心投入的", "pos": "adj.", "sentence": "Her recent findings suggest that older adults immersed in a supportive learning environment can significantly increase their cognitive abilities as well as their confidence in their ability to learn."},
{"word": "competent", "meaning": "有能力的，胜任的", "pos": "adj.", "sentence": "This internalized ageism can lead to beliefs that older adults are less competent, can't learn, and must give up things that are important to them."},
{"word": "grappling", "meaning": "努力解决，搏斗", "pos": "v.", "sentence": "Research shows that elite esports players often experience poor mental health outcomes."},
{"word": "finalize", "meaning": "最终确定", "pos": "v.", "sentence": "In November 2025, Poulus and colleagues convened game publishers, tournament organizers, International Olympic Committee representatives, and mental health experts to finalize nine pillars of mental health support."},
{"word": "flagrant", "meaning": "公然的，明目张胆的", "pos": "adj.", "sentence": "This would be akin to a player committing a flagrant foul in basketball or rushing the mound in baseball."},
{"word": "suboptimal", "meaning": "次优的，不理想的", "pos": "adj.", "sentence": "Researchers are also examining tilt—strong negative emotions that lead to suboptimal decisions during games."},
{"word": "toughness", "meaning": "坚韧，强硬", "pos": "n.", "sentence": "They found that traditional sport psychology measures, like mental toughness and resilience, do not significantly predict competitive achievement in esports."},
{"word": "intense", "meaning": "激烈的，强烈的", "pos": "adj.", "sentence": "Many professional players face intense performance stressors that contribute to burnout and psychological distress."},
{"word": "intervention", "meaning": "干预，介入", "pos": "n.", "sentence": "A mindset-reappraisal intervention that encouraged players to view stress as beneficial lowered players' anxiety and led to faster completion times."},
{"word": "lecturer", "meaning": "讲师", "pos": "n.", "sentence": "Benjamin Sharpe, PhD, a senior lecturer in cognitive psychology and director of the Human Attention Laboratory at the University of Chichester."},
{"word": "obscure", "meaning": "模糊的，不为人知的", "pos": "adj.", "sentence": "Originating from a somewhat obscure rap song in late 2024."},
{"word": "debilitating", "meaning": "使人虚弱的，令人衰弱的", "pos": "adj.", "sentence": "It is a distressing and often debilitating disorder."},
{"word": "accuracy", "meaning": "准确性，精确度", "pos": "n.", "sentence": "Getting players to reconceptualize stress as being beneficial improved shooting accuracy, attentional control, and cognitive effort during high-pressure performance."},
{"word": "credential", "meaning": "资格，证书", "pos": "n.", "sentence": "The Certified Mental Performance Consultant (CMPC) credential has emerged as a pathway into the field for master's-level clinicians."},
{"word": "neutralize", "meaning": "中和，抵消", "pos": "v.", "sentence": "Helps patients learn to coexist with intrusive thoughts without trying to neutralize, avoid, or control them."},
{"word": "perpetuate", "meaning": "使持续，使永久化", "pos": "v.", "sentence": "Sometimes getting treatments that perpetuate the condition."},
{"word": "contamination concerns", "meaning": "对污染的担忧，洁癖", "pos": "n.", "sentence": "From contamination concerns and repeated checking to intrusive moral, sexual, or relationship-related concerns."},
{"word": "ego-syntonic thoughts", "meaning": "自我和谐的想法", "pos": "n.", "sentence": "As opposed to ego-syntonic thoughts or urges, which feel acceptable or desirable."},
{"word": "contamination", "meaning": "污染，污染恐惧", "pos": "n.", "sentence": "Contamination (where a fear of germs or toxins leads to excessive cleaning)."},
{"word": "scrupulosity", "meaning": "道德完美主义，宗教性强迫", "pos": "n.", "sentence": "Scrupulosity (excessive concerns about blasphemy or religious wrongdoing)."},
{"word": "hyperactivity", "meaning": "多动症，过度活跃", "pos": "n.", "sentence": "In children, OCD can be mistaken for attention-deficit/hyperactivity disorder."},
{"word": "incentives tied", "meaning": "挂钩的奖励，激励绑定", "pos": "n.", "sentence": "Such as incentives tied to completing exposures."},
{"word": "accommodation", "meaning": "顺应，配合", "pos": "n.", "sentence": "Providers also work closely with parents to reduce accommodation."},
{"word": "compassionate", "meaning": "富有同情心的，人道的", "pos": "adj.", "sentence": "ERP is probably the most compassionate thing you can do for someone who suffers from OCD."},
{"word": "prescribed", "meaning": "开（药），处方的", "pos": "v.", "sentence": "They are typically prescribed in higher doses than used to treat depression."},
{"word": "upstream", "meaning": "上游的，从源头", "pos": "adj.", "sentence": "This metacognitive approach focuses upstream on how obsessions form."},
{"word": "accountability", "meaning": "问责制，责任", "pos": "n.", "sentence": "Teams were also encouraged to develop their own norms around culture, accountability, and conflict management, fostering self-sufficiency and leadership skills."}
];