const vocabData = [
{"word": "Be vulnerable to", "meaning": "易受……的影响", "pos": "phr.", "sentence": "Children are vulnerable to infections."},
{"word": "By way of", "meaning": "经由；通过……方式", "pos": "phr.", "sentence": "He went to Paris by way of London."},
{"word": "Get rid of", "meaning": "摆脱", "pos": "phr.", "sentence": "We need to get rid of the old furniture."},
{"word": "In light of", "meaning": "鉴于；由于", "pos": "phr.", "sentence": "In light of recent events, we must act."},
{"word": "In vain", "meaning": "徒劳", "pos": "phr.", "sentence": "All his efforts were in vain."},
{"word": "Learn by heart", "meaning": "背诵；熟记", "pos": "phr.", "sentence": "Learn the poem by heart."},
{"word": "Measure up to", "meaning": "符合；达到（标准）", "pos": "phr.", "sentence": "He didn't measure up to expectations."},
{"word": "None the less", "meaning": "尽管如此", "pos": "phr.", "sentence": "He failed; none the less, he tried hard."},
{"word": "On the grounds of", "meaning": "根据；基于（原因）", "pos": "phr.", "sentence": "He was fired on the grounds of misconduct."},
{"word": "Opt for", "meaning": "选择", "pos": "phr.", "sentence": "You can opt for a different plan."},
{"word": "Postpone doing sth.", "meaning": "推迟做某事", "pos": "phr.", "sentence": "We postponed making a decision."},
{"word": "Prior to", "meaning": "在……之前", "pos": "phr.", "sentence": "Prior to the meeting, we had lunch."},
{"word": "Protestant", "meaning": "新教徒", "pos": "n.", "sentence": "Martin Luther was a Protestant leader."},
{"word": "Provide for", "meaning": "供养；规定", "pos": "phr.", "sentence": "He must provide for his family."},
{"word": "Quite a few", "meaning": "相当的", "pos": "phr.", "sentence": "There were quite a few people at the party."},
{"word": "Refer to", "meaning": "提到；查阅；参考", "pos": "phr.", "sentence": "Please refer to the manual for details."},
{"word": "Set about", "meaning": "着手", "pos": "phr.", "sentence": "She set about cleaning the house."},
{"word": "Set aside", "meaning": "留出", "pos": "phr.", "sentence": "Set aside some money for emergencies."},
{"word": "Set down", "meaning": "写下", "pos": "phr.", "sentence": "He set down his thoughts in a diary."},
{"word": "Set off", "meaning": "出发", "pos": "phr.", "sentence": "They set off early in the morning."},
{"word": "Set out", "meaning": "出发", "pos": "phr.", "sentence": "We set out on a long journey."},
{"word": "Set up", "meaning": "建立", "pos": "phr.", "sentence": "They set up a new company."},
{"word": "Stand for", "meaning": "代表", "pos": "phr.", "sentence": "What does this abbreviation stand for?"},
{"word": "Subject to", "meaning": "受制于；易遭受", "pos": "phr.", "sentence": "The plan is subject to approval."},
{"word": "Substitute for", "meaning": "代替", "pos": "phr.", "sentence": "Honey can substitute for sugar."},
{"word": "Take after", "meaning": "像", "pos": "phr.", "sentence": "She takes after her mother."},
{"word": "Take for", "meaning": "误认为", "pos": "phr.", "sentence": "Don't take him for a fool."},
{"word": "Take in", "meaning": "欺骗", "pos": "phr.", "sentence": "He was taken in by the scam."},
{"word": "Take off", "meaning": "起飞", "pos": "phr.", "sentence": "The plane will take off soon."},
{"word": "Take on", "meaning": "承担", "pos": "phr.", "sentence": "He took on more responsibilities."},
{"word": "Take over", "meaning": "接管", "pos": "phr.", "sentence": "She will take over the project."},
{"word": "Take up", "meaning": "从事", "pos": "phr.", "sentence": "He took up golf last year."},
{"word": "Tell from", "meaning": "辨别", "pos": "phr.", "sentence": "Can you tell the original from the copy?"},
{"word": "plunge", "meaning": "投入；猛跌", "pos": "v.", "sentence": "The stock market plunged yesterday."},
{"word": "plurality", "meaning": "多数；多元性", "pos": "n.", "sentence": "A plurality of opinions exists."},
{"word": "pneumonia", "meaning": "肺炎", "pos": "n.", "sentence": "He was diagnosed with pneumonia."},
{"word": "poignant", "meaning": "辛辣的；沉痛的", "pos": "a.", "sentence": "A poignant reminder of the past."},
{"word": "pointer", "meaning": "指针；提示", "pos": "n.", "sentence": "Use the pointer to navigate."},
{"word": "pointless", "meaning": "无意义的", "pos": "a.", "sentence": "The argument was pointless."},
{"word": "poise", "meaning": "姿态", "pos": "n.", "sentence": "She showed great poise under pressure."},
{"word": "poisonous", "meaning": "有毒的", "pos": "a.", "sentence": "Some mushrooms are poisonous."},
{"word": "polarity", "meaning": "极性", "pos": "n.", "sentence": "The polarity of the magnet is important."},
{"word": "polarize", "meaning": "使极化；使分化", "pos": "v.", "sentence": "The issue polarized the community."},
{"word": "policymaker", "meaning": "决策者", "pos": "n.", "sentence": "Policymakers must consider all options."},
{"word": "poll", "meaning": "民意测验；投票", "pos": "n.", "sentence": "The poll showed strong support."},
{"word": "pollen", "meaning": "花粉", "pos": "n.", "sentence": "Pollen causes allergies in spring."},
{"word": "pollutant", "meaning": "污染物", "pos": "n.", "sentence": "Air pollutants affect health."},
{"word": "pollute", "meaning": "污染", "pos": "v.", "sentence": "Factories pollute the environment."},
{"word": "pompous", "meaning": "傲慢的；华而不实的", "pos": "a.", "sentence": "His pompous speech annoyed everyone."},
{"word": "ponder", "meaning": "沉思", "pos": "v.", "sentence": "He pondered the question carefully."},
{"word": "poorly", "meaning": "贫穷地；拙劣地", "pos": "ad.", "sentence": "The project was poorly managed."},
{"word": "populous", "meaning": "人口稠密的", "pos": "a.", "sentence": "China is a populous country."},
{"word": "porch", "meaning": "门廊", "pos": "n.", "sentence": "They sat on the porch talking."},
{"word": "porous", "meaning": "有孔的；能渗透的", "pos": "a.", "sentence": "Sponge is a porous material."},
{"word": "portable", "meaning": "轻便的；便携的", "pos": "adj.", "sentence": "This device is portable."},
{"word": "portfolio", "meaning": "公事包；文件夹；投资组合", "pos": "n.", "sentence": "She manages an investment portfolio."},
{"word": "portrayal", "meaning": "描绘", "pos": "n.", "sentence": "His portrayal of the character was excellent."},
{"word": "posh", "meaning": "优雅的；豪华的", "pos": "adj.", "sentence": "They stayed at a posh hotel."},
{"word": "possessive", "meaning": "所有格的；占有欲强的", "pos": "adj.", "sentence": "She is possessive about her books."},
{"word": "postage", "meaning": "邮资", "pos": "n.", "sentence": "The postage cost is increasing."},
{"word": "postal", "meaning": "邮政的", "pos": "adj.", "sentence": "The postal service is reliable."},
{"word": "posterity", "meaning": "后代", "pos": "n.", "sentence": "We must preserve this for posterity."},
{"word": "postgraduate", "meaning": "研究生；毕业后的", "pos": "n./adj.", "sentence": "She is a postgraduate student."},
{"word": "posthumous", "meaning": "死后的", "pos": "a.", "sentence": "He received a posthumous award."},
{"word": "postpone", "meaning": "推迟", "pos": "v.", "sentence": "We had to postpone the meeting."},
{"word": "postponement", "meaning": "延期", "pos": "n.", "sentence": "The postponement caused problems."},
{"word": "postscript", "meaning": "附言", "pos": "n.", "sentence": "She added a postscript to the letter."},
{"word": "postulate", "meaning": "假设", "pos": "v.", "sentence": "Scientists postulate new theories."},
{"word": "posture", "meaning": "姿势；态度", "pos": "n.", "sentence": "Good posture is important for health."},
{"word": "potency", "meaning": "力量；潜能", "pos": "n.", "sentence": "The potency of the drug is high."},
{"word": "potentiality", "meaning": "潜力", "pos": "n.", "sentence": "The potentiality for growth is immense."},
{"word": "pounce", "meaning": "扑向", "pos": "v.", "sentence": "The cat pounced on the mouse."},
{"word": "poverty", "meaning": "贫困", "pos": "n.", "sentence": "Poverty remains a global issue."},
{"word": "practicable", "meaning": "可行的", "pos": "a.", "sentence": "The plan seems practicable."},
{"word": "practical", "meaning": "实际的；实用的", "pos": "a.", "sentence": "Give me a practical solution."},
{"word": "practitioner", "meaning": "从业者；执业医生/律师", "pos": "n.", "sentence": "Consult a medical practitioner."},
{"word": "pragmatic", "meaning": "务实的", "pos": "a.", "sentence": "We need a pragmatic approach."},
{"word": "praiseworthy", "meaning": "值得称赞的", "pos": "a.", "sentence": "His efforts are praiseworthy."},
{"word": "prearious", "meaning": "不稳固的；危险的", "pos": "a.", "sentence": "The situation is precarious."},
{"word": "precaution", "meaning": "预防措施", "pos": "n.", "sentence": "Take necessary precautions."},
{"word": "precedence", "meaning": "优先；领先", "pos": "n.", "sentence": "Safety takes precedence over speed."},
{"word": "precedent", "meaning": "先例", "pos": "n.", "sentence": "This sets a dangerous precedent."},
{"word": "preceding", "meaning": "在前的", "pos": "a.", "sentence": "The preceding chapter was informative."},
{"word": "precipice", "meaning": "悬崖", "pos": "n.", "sentence": "They stood at the edge of the precipice."},
{"word": "precipitate", "meaning": "促成；猛摔", "pos": "v.", "sentence": "The decision precipitated a crisis."},
{"word": "precipitation", "meaning": "降水；仓促", "pos": "n.", "sentence": "Heavy precipitation is expected."},
{"word": "precision", "meaning": "精确", "pos": "n.", "sentence": "The work requires great precision."},
{"word": "preclude", "meaning": "排除；阻止", "pos": "v.", "sentence": "This does not preclude other options."},
{"word": "precocious", "meaning": "早熟的", "pos": "a.", "sentence": "A precocious child learns quickly."},
{"word": "predecessor", "meaning": "前任；前辈", "pos": "n.", "sentence": "He succeeded his predecessor."},
{"word": "relieve", "meaning": "减轻；解除", "pos": "v.", "sentence": "This medicine relieves pain."},
{"word": "reluctance", "meaning": "不情愿", "pos": "n.", "sentence": "He showed reluctance to accept."},
{"word": "remedy", "meaning": "补救；治疗法", "pos": "n.", "sentence": "There is a remedy for every problem."},
{"word": "remnant", "meaning": "残余物", "pos": "n.", "sentence": "Only remnants of the building remain."},
{"word": "renaissance", "meaning": "文艺复兴；再生", "pos": "n.", "sentence": "The Renaissance was a period of rebirth."},
{"word": "renovate", "meaning": "翻新；修复", "pos": "v.", "sentence": "They plan to renovate the house."},
{"word": "repeal", "meaning": "废除；撤销", "pos": "v./n.", "sentence": "The law was repealed last year."},
{"word": "repel", "meaning": "击退；抵制", "pos": "v.", "sentence": "The coating repels water."},
{"word": "repetitive", "meaning": "重复的", "pos": "a.", "sentence": "The work is repetitive and boring."},
{"word": "reproduce", "meaning": "繁殖；复制", "pos": "v.", "sentence": "Cells reproduce by division."}
];
