const vocabData = [
{"word": "stipulate", "meaning": "规定；约定", "pos": "v.", "sentence": "The contract stipulates the terms of employment."},
{"word": "strategy", "meaning": "战略；策略", "pos": "n.", "sentence": "The company developed a new marketing strategy."},
{"word": "stride", "meaning": "大步走；进展", "pos": "v./n.", "sentence": "He took long strides to catch up."},
{"word": "strife", "meaning": "冲突；争吵", "pos": "n.", "sentence": "Political strife divided the nation."},
{"word": "striking", "meaning": "显著的；引人注目的", "pos": "a.", "sentence": "There is a striking resemblance between them."},
{"word": "stringent", "meaning": "严格的；紧迫的", "pos": "a.", "sentence": "The bank has stringent lending criteria."},
{"word": "subjective", "meaning": "主观的", "pos": "adj.", "sentence": "Beauty is subjective."},
{"word": "subjectivity", "meaning": "主观性", "pos": "n.", "sentence": "The report was criticized for its subjectivity."},
{"word": "subpoena", "meaning": "传票；传唤", "pos": "n./v.", "sentence": "He received a subpoena to testify."},
{"word": "substantiate", "meaning": "证实", "pos": "v.", "sentence": "Can you substantiate your claims?"},
{"word": "successor", "meaning": "继承者", "pos": "n.", "sentence": "She was named as his successor."},
{"word": "succinct", "meaning": "简洁的", "pos": "a.", "sentence": "His explanation was succinct and clear."},
{"word": "succumb", "meaning": "屈服；死于", "pos": "v.", "sentence": "He succumbed to the pressure."},
{"word": "superficial", "meaning": "表面的；肤浅的", "pos": "a.", "sentence": "The wound is only superficial."},
{"word": "superfluous", "meaning": "多余的", "pos": "a.", "sentence": "Remove all superfluous details."},
{"word": "superiority", "meaning": "优越性", "pos": "n.", "sentence": "Their technological superiority is evident."},
{"word": "superstition", "meaning": "迷信", "pos": "n.", "sentence": "The old woman believed in superstition."},
{"word": "supplement", "meaning": "补充；增刊", "pos": "n./v.", "sentence": "Vitamin supplements can help fill nutritional gaps."},
{"word": "suppression", "meaning": "镇压；抑制", "pos": "n.", "sentence": "The suppression of dissent continues."},
{"word": "surpass", "meaning": "超过；胜过", "pos": "v.", "sentence": "His skills surpass those of his peers."},
{"word": "surplus", "meaning": "过剩；盈余", "pos": "n.", "sentence": "The country has a trade surplus."},
{"word": "suspend", "meaning": "悬挂；暂停；推迟", "pos": "v.", "sentence": "The game was suspended due to rain."},
{"word": "suspense", "meaning": "悬念；焦虑", "pos": "n.", "sentence": "The movie kept us in suspense."},
{"word": "sustain", "meaning": "维持；支撑；遭受", "pos": "v.", "sentence": "The economy could not sustain the growth."},
{"word": "swindle", "meaning": "诈骗", "pos": "v./n.", "sentence": "He was arrested for a major swindle."},
{"word": "symptom", "meaning": "症状；征兆", "pos": "n.", "sentence": "Fever is a common symptom of flu."},
{"word": "synopsis", "meaning": "大纲；梗概", "pos": "n.", "sentence": "Read the synopsis before watching the movie."},
{"word": "synthetic", "meaning": "合成的；人造的", "pos": "adj.", "sentence": "The fabric is made of synthetic fibers."},
{"word": "tackle", "meaning": "解决；应付；对付", "pos": "v.", "sentence": "We need to tackle this problem immediately."},
{"word": "tactics", "meaning": "战术；策略", "pos": "n.", "sentence": "The team used different tactics in the second half."},
{"word": "tangible", "meaning": "有形的；切实的", "pos": "adj.", "sentence": "We need tangible evidence."},
{"word": "tariff", "meaning": "关税；价目表", "pos": "n.", "sentence": "The government raised import tariffs."},
{"word": "tedious", "meaning": "乏味的；单调的", "pos": "a.", "sentence": "The task became tedious after a while."},
{"word": "temperament", "meaning": "气质；性格", "pos": "n.", "sentence": "She has a calm temperament."},
{"word": "temptation", "meaning": "诱惑", "pos": "n.", "sentence": "He resisted the temptation to eat cake."},
{"word": "tenancy", "meaning": "租赁；租期", "pos": "n.", "sentence": "The tenancy agreement expires next month."},
{"word": "tenant", "meaning": "承租人；房客", "pos": "n.", "sentence": "The tenant pays rent on time."},
{"word": "tentative", "meaning": "试验性的；暂定的", "pos": "a.", "sentence": "These are just tentative plans."},
{"word": "tenure", "meaning": "任期；终身职位", "pos": "n.", "sentence": "He was granted tenure at the university."},
{"word": "terminate", "meaning": "停止；结束", "pos": "v.", "sentence": "The contract will terminate next month."},
{"word": "terminology", "meaning": "术语", "pos": "n.", "sentence": "Learn the medical terminology first."},
{"word": "terrestrial", "meaning": "陆地的；地球的", "pos": "a.", "sentence": "Terrestrial animals live on land."},
{"word": "territory", "meaning": "领土；领域", "pos": "n.", "sentence": "The animals defend their territory."},
{"word": "testify", "meaning": "作证；表明", "pos": "v.", "sentence": "She agreed to testify in court."},
{"word": "testimony", "meaning": "证言；证据", "pos": "n.", "sentence": "His testimony was crucial to the case."},
{"word": "texture", "meaning": "质地；结构", "pos": "n.", "sentence": "The texture of the fabric is smooth."},
{"word": "therapeutic", "meaning": "治疗的", "pos": "a.", "sentence": "Music has therapeutic effects."},
{"word": "therapy", "meaning": "治疗；疗法", "pos": "n.", "sentence": "She is undergoing physical therapy."},
{"word": "threshold", "meaning": "门槛；开端", "pos": "n.", "sentence": "We are on the threshold of a new era."},
{"word": "thrift", "meaning": "节俭", "pos": "n.", "sentence": "His thrift helped him save money."},
{"word": "thrive", "meaning": "兴旺；繁荣", "pos": "v.", "sentence": "The business thrived in the new location."},
{"word": "token", "meaning": "象征；代币；标志", "pos": "n.", "sentence": "Please accept this gift as a token of appreciation."},
{"word": "tolerable", "meaning": "可忍受的", "pos": "a.", "sentence": "The pain is tolerable now."},
{"word": "tolerance", "meaning": "宽容；忍耐力", "pos": "n.", "sentence": "We need to show tolerance to different views."},
{"word": "tolerate", "meaning": "容忍", "pos": "v.", "sentence": "I cannot tolerate such behavior."},
{"word": "toll", "meaning": "通行费；伤亡人数", "pos": "n.", "sentence": "The death toll rose to hundreds."},
{"word": "tournament", "meaning": "锦标赛", "pos": "n.", "sentence": "The tennis tournament starts tomorrow."}
];
