const vocabData = [
{"word": "Be vulnerable to", "meaning": "易受……的影响", "pos": "phr.", "sentence": "Children are vulnerable to infections."},
{"word": "By way of", "meaning": "经由；通过……方式", "pos": "phr.", "sentence": "He went to Paris by way of London."},
{"word": "Get rid of", "meaning": "摆脱", "pos": "phr.", "sentence": "I need to get rid of these old clothes."},
{"word": "In light of", "meaning": "鉴于；由于", "pos": "phr.", "sentence": "In light of recent events, we changed our plans."},
{"word": "In vain", "meaning": "徒劳", "pos": "phr.", "sentence": "All his efforts were in vain."},
{"word": "Learn by heart", "meaning": "背诵；熟记", "pos": "phr.", "sentence": "She learned the poem by heart."},
{"word": "Measure up to", "meaning": "符合；达到（标准）", "pos": "phr.", "sentence": "He didn't measure up to expectations."},
{"word": "None the less", "meaning": "尽管如此", "pos": "phr.", "sentence": "It was raining; none the less, we went out."},
{"word": "On the grounds of", "meaning": "根据；基于（原因）", "pos": "phr.", "sentence": "He resigned on the grounds of ill health."},
{"word": "Opt for", "meaning": "选择", "pos": "phr.", "sentence": "She opted for the blue dress."},
{"word": "Pacific", "meaning": "太平洋的；和平的", "pos": "adj.", "sentence": "The Pacific Ocean is the largest ocean."},
{"word": "Postpone doing sth.", "meaning": "推迟做某事", "pos": "phr.", "sentence": "He postponed making a decision."},
{"word": "Prior to", "meaning": "在……之前", "pos": "phr.", "sentence": "Prior to the meeting, we reviewed the documents."},
{"word": "Protestant", "meaning": "新教徒", "pos": "n.", "sentence": "Many Protestants live in this region."},
{"word": "Provide for", "meaning": "供养；规定", "pos": "phr.", "sentence": "He provides for his family."},
{"word": "Quite a few", "meaning": "相当的", "pos": "phr.", "sentence": "There were quite a few people at the party."},
{"word": "Refer to", "meaning": "提到；查阅；参考", "pos": "phr.", "sentence": "Please refer to the manual for instructions."},
{"word": "Set about", "meaning": "着手", "pos": "phr.", "sentence": "He set about cleaning the house."},
{"word": "Set aside", "meaning": "留出", "pos": "phr.", "sentence": "She set aside some money for emergencies."},
{"word": "Set down", "meaning": "写下", "pos": "phr.", "sentence": "He set down his thoughts in a diary."},
{"word": "Set off", "meaning": "出发", "pos": "phr.", "sentence": "We set off early in the morning."},
{"word": "Set out", "meaning": "出发", "pos": "phr.", "sentence": "They set out on a long journey."},
{"word": "Set up", "meaning": "建立", "pos": "phr.", "sentence": "She set up her own business."},
{"word": "Stand for", "meaning": "代表", "pos": "phr.", "sentence": "What does this abbreviation stand for?"},
{"word": "Subject to", "meaning": "受制于；易遭受", "pos": "phr.", "sentence": "Prices are subject to change."},
{"word": "Substitute for", "meaning": "代替", "pos": "phr.", "sentence": "Honey can substitute for sugar."},
{"word": "Take after", "meaning": "像", "pos": "phr.", "sentence": "She takes after her mother."},
{"word": "Take for", "meaning": "误认为", "pos": "phr.", "sentence": "Don't take him for a fool."},
{"word": "Take in", "meaning": "欺骗", "pos": "phr.", "sentence": "I was taken in by his lies."},
{"word": "Take off", "meaning": "起飞", "pos": "phr.", "sentence": "The plane took off on time."},
{"word": "Take on", "meaning": "承担", "pos": "phr.", "sentence": "He took on more responsibilities."},
{"word": "Take over", "meaning": "接管", "pos": "phr.", "sentence": "She will take over the company."},
{"word": "Take up", "meaning": "从事", "pos": "phr.", "sentence": "He took up golf last year."},
{"word": "Tell from", "meaning": "辨别", "pos": "phr.", "sentence": "I can't tell him from his brother."},
{"word": "Turn down", "meaning": "拒绝；调低", "pos": "phr.", "sentence": "He turned down the job offer."},
{"word": "Turn in", "meaning": "上交；睡觉", "pos": "phr.", "sentence": "Turn in your homework by Friday."},
{"word": "Turn on", "meaning": "打开", "pos": "phr.", "sentence": "Please turn on the light."},
{"word": "Turn out", "meaning": "结果是；生产", "pos": "phr.", "sentence": "It turned out to be a good decision."},
{"word": "Turn over", "meaning": "翻转；移交", "pos": "phr.", "sentence": "Please turn over the page."},
{"word": "Turn up", "meaning": "出现；调大", "pos": "phr.", "sentence": "He turned up late for the meeting."},
{"word": "Use up", "meaning": "用完", "pos": "phr.", "sentence": "We used up all the supplies."},
{"word": "Work out", "meaning": "锻炼；解决", "pos": "phr.", "sentence": "She works out at the gym every day."},
{"word": "Yield to", "meaning": "屈服于；让步", "pos": "phr.", "sentence": "He refused to yield to pressure."},
{"word": "participate", "meaning": "参加", "pos": "v.", "sentence": "She participated in the discussion."},
{"word": "particle", "meaning": "微粒；极小量", "pos": "n.", "sentence": "Dust particles floated in the air."},
{"word": "partition", "meaning": "划分；隔断", "pos": "n.", "sentence": "They installed a partition in the room."},
{"word": "passive", "meaning": "被动的", "pos": "adj.", "sentence": "He took a passive role in the project."},
{"word": "pastime", "meaning": "消遣；娱乐", "pos": "n.", "sentence": "Reading is her favorite pastime."},
{"word": "pasture", "meaning": "牧场", "pos": "n.", "sentence": "The cows grazed in the pasture."},
{"word": "patent", "meaning": "专利；明显的", "pos": "n./adj.", "sentence": "He applied for a patent."},
{"word": "paternal", "meaning": "父亲的", "pos": "adj.", "sentence": "He has a strong paternal instinct."},
{"word": "paternity", "meaning": "父亲身份；父系", "pos": "n.", "sentence": "The paternity test confirmed he was the father."},
{"word": "pathology", "meaning": "病理学", "pos": "n.", "sentence": "She specializes in pathology."},
{"word": "patience", "meaning": "耐心", "pos": "n.", "sentence": "Teaching requires a lot of patience."},
{"word": "patrimony", "meaning": "遗产", "pos": "n.", "sentence": "The castle is part of his patrimony."},
{"word": "patriot", "meaning": "爱国者", "pos": "n.", "sentence": "He was considered a true patriot."},
{"word": "patriotic", "meaning": "爱国者的", "pos": "adj.", "sentence": "The song is very patriotic."},
{"word": "patrol", "meaning": "巡逻", "pos": "v./n.", "sentence": "The police patrol the streets at night."},
{"word": "patronage", "meaning": "资助；光顾", "pos": "n.", "sentence": "The artist relied on royal patronage."},
{"word": "paucity", "meaning": "缺乏", "pos": "n.", "sentence": "There is a paucity of evidence."},
{"word": "pavement", "meaning": "人行道", "pos": "n.", "sentence": "Walk on the pavement, not the road."},
{"word": "pedal", "meaning": "踏板；骑自行车", "pos": "n./v.", "sentence": "Press the pedal to accelerate."},
{"word": "pedant", "meaning": "迂腐的人；学究", "pos": "n.", "sentence": "He is such a pedant about grammar."},
{"word": "pedestrian", "meaning": "行人；徒步的；乏味的", "pos": "n./adj.", "sentence": "The pedestrian crossed the street."},
{"word": "pedigree", "meaning": "血统；家谱", "pos": "n.", "sentence": "The dog has an excellent pedigree."},
{"word": "peel", "meaning": "剥皮；果皮", "pos": "v./n.", "sentence": "Peel the potatoes before cooking."},
{"word": "peer", "meaning": "同龄人；贵族；凝视", "pos": "n./v.", "sentence": "He was respected by his peers."},
{"word": "penalty", "meaning": "处罚；罚款", "pos": "n.", "sentence": "The penalty for speeding is a fine."},
{"word": "penance", "meaning": "忏悔", "pos": "n.", "sentence": "He did penance for his sins."},
{"word": "pendant", "meaning": "坠儿", "pos": "n.", "sentence": "She wore a beautiful pendant."},
{"word": "pending", "meaning": "待定的；直到", "pos": "adj./prep.", "sentence": "The decision is still pending."},
{"word": "penetrate", "meaning": "穿透；渗透", "pos": "v.", "sentence": "The bullet penetrated the wall."},
{"word": "pension", "meaning": "养老金；津贴", "pos": "n.", "sentence": "He receives a monthly pension."},
{"word": "pensioner", "meaning": "领取养老金的人", "pos": "n.", "sentence": "Many pensioners live on fixed incomes."},
{"word": "pensive", "meaning": "忧思的", "pos": "adj.", "sentence": "She sat in a pensive mood."},
{"word": "pentagon", "meaning": "五角形", "pos": "n.", "sentence": "A pentagon has five sides."},
{"word": "penultimate", "meaning": "倒数第二的", "pos": "adj.", "sentence": "This is the penultimate chapter."},
{"word": "penury", "meaning": "贫困", "pos": "n.", "sentence": "He lived in penury for many years."},
{"word": "perceptive", "meaning": "敏锐的", "pos": "adj.", "sentence": "She is a perceptive observer."},
{"word": "perch", "meaning": "栖息", "pos": "v.", "sentence": "The bird perched on the branch."},
{"word": "perennial", "meaning": "常年的；四季不断的", "pos": "adj.", "sentence": "Roses are perennial plants."},
{"word": "perfectionist", "meaning": "完美主义者", "pos": "n.", "sentence": "He is a perfectionist in his work."},
{"word": "perforate", "meaning": "打孔", "pos": "v.", "sentence": "Perforate the paper along the dotted line."},
{"word": "peripheral", "meaning": "周边的；次要的", "pos": "adj.", "sentence": "These are peripheral issues."},
{"word": "perish", "meaning": "毁灭；死亡", "pos": "v.", "sentence": "Many animals perish in forest fires."},
{"word": "permanent", "meaning": "永久的；固定的", "pos": "adj.", "sentence": "He has a permanent job."},
{"word": "permeate", "meaning": "弥漫；渗透", "pos": "v.", "sentence": "The smell of coffee permeated the room."},
{"word": "permissible", "meaning": "允许的", "pos": "adj.", "sentence": "Is it permissible to park here?"},
{"word": "perpetual", "meaning": "永久的", "pos": "adj.", "sentence": "They signed a perpetual lease."},
{"word": "perplexity", "meaning": "困惑", "pos": "n.", "sentence": "She looked at him in perplexity."},
{"word": "persecution", "meaning": "迫害", "pos": "n.", "sentence": "They fled religious persecution."},
{"word": "perseverance", "meaning": "毅力", "pos": "n.", "sentence": "Success requires perseverance."},
{"word": "personnel", "meaning": "全体人员；人事部门", "pos": "n.", "sentence": "The personnel department handles hiring."},
{"word": "perspective", "meaning": "视角；透视", "pos": "n.", "sentence": "Let's look at this from a different perspective."},
];
