const vocabData = [
{"word": "participate", "meaning": "参加", "pos": "v.", "sentence": "Everyone should participate."},
{"word": "particle", "meaning": "微粒；极小量", "pos": "n.", "sentence": "A tiny particle of dust."},
{"word": "partition", "meaning": "划分；隔断", "pos": "n.", "sentence": "The partition divided the room."},
{"word": "passive", "meaning": "被动的", "pos": "adj.", "sentence": "He was passive in the discussion."},
{"word": "pastime", "meaning": "消遣；娱乐", "pos": "n.", "sentence": "Reading is my favorite pastime."},
{"word": "pasture", "meaning": "牧场", "pos": "n.", "sentence": "Cows graze in the pasture."},
{"word": "patent", "meaning": "专利；明显的", "pos": "n./adj.", "sentence": "Apply for a patent."},
{"word": "paternal", "meaning": "父亲的", "pos": "adj.", "sentence": "Paternal love is strong."},
{"word": "paternity", "meaning": "父亲身份；父系", "pos": "n.", "sentence": "A paternity test."},
{"word": "pathology", "meaning": "病理学", "pos": "n.", "sentence": "She studies pathology."},
{"word": "patience", "meaning": "耐心", "pos": "n.", "sentence": "Have patience."},
{"word": "patrimony", "meaning": "遗产", "pos": "n.", "sentence": "The family patrimony."},
{"word": "peel", "meaning": "剥皮；果皮", "pos": "v./n.", "sentence": "Peel the apple."},
{"word": "peer", "meaning": "同龄人；贵族；凝视", "pos": "n./v.", "sentence": "Peer pressure is strong."},
{"word": "penalty", "meaning": "处罚；罚款", "pos": "n.", "sentence": "A heavy penalty."},
{"word": "penance", "meaning": "忏悔", "pos": "n.", "sentence": "Do penance for your sins."},
{"word": "pendant", "meaning": "坠儿", "pos": "n.", "sentence": "A beautiful pendant."},
{"word": "pending", "meaning": "待定的；直到", "pos": "adj./prep.", "sentence": "The case is still pending."},
{"word": "penetrate", "meaning": "穿透；渗透", "pos": "v.", "sentence": "Light penetrated the darkness."},
{"word": "pension", "meaning": "养老金；津贴", "pos": "n.", "sentence": "A generous pension."},
{"word": "pensioner", "meaning": "领取养老金的人", "pos": "n.", "sentence": "He is a pensioner now."},
{"word": "pensive", "meaning": "忧思的", "pos": "adj.", "sentence": "A pensive mood."},
{"word": "pentagon", "meaning": "五角形", "pos": "n.", "sentence": "A pentagon has five sides."},
{"word": "penultimate", "meaning": "倒数第二的", "pos": "adj.", "sentence": "The penultimate chapter."},
{"word": "penury", "meaning": "贫困", "pos": "n.", "sentence": "Living in penury."},
{"word": "perceptive", "meaning": "敏锐的", "pos": "adj.", "sentence": "A perceptive observer."},
{"word": "perch", "meaning": "栖息", "pos": "v.", "sentence": "Birds perch on branches."},
{"word": "perennial", "meaning": "常年的；四季不断的", "pos": "adj.", "sentence": "A perennial problem."},
{"word": "perfectionist", "meaning": "完美主义者", "pos": "n.", "sentence": "She is a perfectionist."},
{"word": "perforate", "meaning": "打孔", "pos": "v.", "sentence": "Perforate the paper."},
{"word": "peripheral", "meaning": "周边的；次要的", "pos": "adj.", "sentence": "Peripheral vision."},
{"word": "perish", "meaning": "毁灭；死亡", "pos": "v.", "sentence": "Flowers perish quickly."},
{"word": "permanent", "meaning": "永久的；固定的", "pos": "adj.", "sentence": "A permanent job."},
{"word": "permeate", "meaning": "弥漫；渗透", "pos": "v.", "sentence": "The smell permeated the room."},
{"word": "permissible", "meaning": "允许的", "pos": "adj.", "sentence": "It is permissible to ask."},
{"word": "perpetual", "meaning": "永久的", "pos": "a.", "sentence": "Perpetual motion."},
{"word": "perplexity", "meaning": "困惑", "pos": "n.", "sentence": "Filled with perplexity."},
{"word": "persecution", "meaning": "迫害", "pos": "n.", "sentence": "Religious persecution."},
{"word": "perseverance", "meaning": "毅力", "pos": "n.", "sentence": "Perseverance leads to success."},
{"word": "personnel", "meaning": "全体人员；人事部门", "pos": "n.", "sentence": "Personnel department."},
{"word": "perspective", "meaning": "视角；透视", "pos": "n.", "sentence": "From a new perspective."},
{"word": "perspiration", "meaning": "汗水", "pos": "n.", "sentence": "Drops of perspiration."},
{"word": "perspire", "meaning": "出汗", "pos": "v.", "sentence": "He began to perspire."},
{"word": "persuade", "meaning": "说服", "pos": "v.", "sentence": "Persuade him to stay."},
{"word": "persuasion", "meaning": "说服", "pos": "n.", "sentence": "The art of persuasion."},
{"word": "pertinent", "meaning": "相关的；中肯的", "pos": "adj.", "sentence": "A pertinent question."},
{"word": "pervasive", "meaning": "普遍的；弥漫的", "pos": "adj.", "sentence": "Pervasive influence."},
{"word": "pessimism", "meaning": "悲观主义", "pos": "n.", "sentence": "Don't fall into pessimism."},
{"word": "pessimist", "meaning": "悲观主义者", "pos": "n.", "sentence": "He is a pessimist."},
{"word": "pessimistic", "meaning": "悲观的", "pos": "adj.", "sentence": "A pessimistic view."},
{"word": "pesticide", "meaning": "杀虫剂", "pos": "n.", "sentence": "Use pesticide carefully."},
{"word": "pestilence", "meaning": "瘟疫", "pos": "n.", "sentence": "The pestilence spread."},
{"word": "petition", "meaning": "请愿书", "pos": "n./v.", "sentence": "Sign the petition."},
{"word": "petroleum", "meaning": "石油", "pos": "n.", "sentence": "Petroleum industry."},
{"word": "petty", "meaning": "琐碎的", "pos": "adj.", "sentence": "Petty arguments."},
{"word": "phantom", "meaning": "幽灵；幻觉", "pos": "n.", "sentence": "A phantom appeared."},
{"word": "pharmaceutical", "meaning": "制药的", "pos": "adj.", "sentence": "Pharmaceutical companies."},
{"word": "pharmacist", "meaning": "药剂师", "pos": "n.", "sentence": "Consult the pharmacist."},
{"word": "pharmacy", "meaning": "药房", "pos": "n.", "sentence": "Go to the pharmacy."},
{"word": "phenomenal", "meaning": "显著的；现象的", "pos": "a.", "sentence": "A phenomenal success."},
{"word": "phenomenon", "meaning": "现象", "pos": "n.", "sentence": "A strange phenomenon."},
{"word": "philanthropic", "meaning": "慈善的", "pos": "a.", "sentence": "Philanthropic activities."},
{"word": "philanthropist", "meaning": "慈善家", "pos": "n.", "sentence": "A famous philanthropist."},
{"word": "philosophy", "meaning": "哲学", "pos": "n.", "sentence": "Study philosophy."},
{"word": "phobia", "meaning": "恐惧症", "pos": "n.", "sentence": "He has a phobia of spiders."},
{"word": "phonetic", "meaning": "语音的", "pos": "a.", "sentence": "Phonetic symbols."},
{"word": "phosphate", "meaning": "磷酸盐", "pos": "n.", "sentence": "Phosphate fertilizer."},
{"word": "physician", "meaning": "内科医生", "pos": "n.", "sentence": "Consult a physician."},
{"word": "physicist", "meaning": "物理学家", "pos": "n.", "sentence": "A famous physicist."},
{"word": "physiological", "meaning": "生理的", "pos": "a.", "sentence": "Physiological changes."},
{"word": "physiology", "meaning": "生理学", "pos": "n.", "sentence": "Human physiology."},
{"word": "physique", "meaning": "体格", "pos": "n.", "sentence": "A strong physique."},
{"word": "picturesque", "meaning": "如画的", "pos": "a.", "sentence": "A picturesque village."},
{"word": "pierce", "meaning": "刺穿", "pos": "v.", "sentence": "Pierce the veil."},
{"word": "piety", "meaning": "虔诚", "pos": "n.", "sentence": "Filial piety."},
{"word": "pigment", "meaning": "色素", "pos": "n.", "sentence": "Skin pigment."},
{"word": "pilgrimage", "meaning": "朝圣", "pos": "n.", "sentence": "Go on a pilgrimage."},
{"word": "pillar", "meaning": "柱子；中流砥柱", "pos": "n.", "sentence": "A pillar of society."},
{"word": "pinnacle", "meaning": "顶峰", "pos": "n.", "sentence": "Reach the pinnacle."},
{"word": "pinpoint", "meaning": "精确指出", "pos": "v.", "sentence": "Pinpoint the problem."},
{"word": "pious", "meaning": "虔诚的", "pos": "a.", "sentence": "A pious believer."},
{"word": "pipeline", "meaning": "管道", "pos": "n.", "sentence": "Build a pipeline."},
{"word": "piracy", "meaning": "海盗行为；盗版", "pos": "n.", "sentence": "Software piracy."},
{"word": "pirate", "meaning": "海盗；盗版者", "pos": "n.", "sentence": "A notorious pirate."},
{"word": "piston", "meaning": "活塞", "pos": "n.", "sentence": "Engine piston."},
{"word": "pivotal", "meaning": "枢轴的；关键的", "pos": "adj.", "sentence": "A pivotal moment."},
{"word": "plagiarism", "meaning": "剽窃；抄袭", "pos": "n.", "sentence": "Accused of plagiarism."},
{"word": "plague", "meaning": "瘟疫；灾祸", "pos": "n./v.", "sentence": "The plague spread."},
{"word": "planetary", "meaning": "行星的", "pos": "adj.", "sentence": "Planetary motion."},
{"word": "plankton", "meaning": "浮游生物", "pos": "n.", "sentence": "Marine plankton."},
{"word": "plantation", "meaning": "种植园", "pos": "n.", "sentence": "A tea plantation."},
{"word": "plaque", "meaning": "匾额；血小板", "pos": "n.", "sentence": "A commemorative plaque."},
{"word": "plasma", "meaning": "血浆", "pos": "n.", "sentence": "Blood plasma."},
{"word": "plateau", "meaning": "高原；停滞期", "pos": "n.", "sentence": "Reach a plateau."},
{"word": "plausible", "meaning": "似乎合理的", "pos": "a.", "sentence": "A plausible excuse."},
{"word": "plead", "meaning": "恳求；申辩", "pos": "v.", "sentence": "Plead for mercy."},
{"word": "pledge", "meaning": "保证；誓言", "pos": "n./v.", "sentence": "Make a pledge."},
{"word": "plentiful", "meaning": "丰富的", "pos": "a.", "sentence": "Plentiful resources."},
{"word": "plethora", "meaning": "过多；过量", "pos": "n.", "sentence": "A plethora of options."},
{"word": "plight", "meaning": "困境", "pos": "n.", "sentence": "In a difficult plight."}
];
