const vocabData = [
{"word": "oppress", "meaning": "压迫", "pos": "v.", "sentence": "The dictator oppressed his people for decades."},
{"word": "oppression", "meaning": "压迫", "pos": "n.", "sentence": "They fought against oppression and injustice."},
{"word": "opt", "meaning": "选择", "pos": "v.", "sentence": "You can opt out of the program at any time."},
{"word": "optical", "meaning": "光学的；视觉的", "pos": "adj.", "sentence": "The optical illusion fooled everyone."},
{"word": "optional", "meaning": "可选择的", "pos": "adj.", "sentence": "Attendance at the event is optional."},
{"word": "opulence", "meaning": "富裕；丰富", "pos": "n.", "sentence": "The palace was a symbol of opulence and luxury."},
{"word": "opulent", "meaning": "豪华的；丰富的", "pos": "adj.", "sentence": "They dined in an opulent restaurant."},
{"word": "oral", "meaning": "口头的", "pos": "adj.", "sentence": "The exam includes both written and oral sections."},
{"word": "orbital", "meaning": "轨道的", "pos": "adj.", "sentence": "The satellite entered its orbital path."},
{"word": "orchestrate", "meaning": "精心策划；编管弦乐", "pos": "v.", "sentence": "He orchestrated a surprise party for her birthday."},
{"word": "ordeal", "meaning": "严峻考验", "pos": "n.", "sentence": "The interview was quite an ordeal."},
{"word": "orderly", "meaning": "整齐的", "pos": "adj.", "sentence": "The room was neat and orderly."},
{"word": "ordinary", "meaning": "普通的", "pos": "adj.", "sentence": "It was just an ordinary day."},
{"word": "organic", "meaning": "有机的；器官的", "pos": "adj.", "sentence": "They buy organic vegetables."},
{"word": "organism", "meaning": "有机体；生物", "pos": "n.", "sentence": "Every organism plays a role in the ecosystem."},
{"word": "orientation", "meaning": "方向；定位；培训", "pos": "n.", "sentence": "New employees attend an orientation session."},
{"word": "originality", "meaning": "创意；独创性", "pos": "n.", "sentence": "The artist is known for her originality."},
{"word": "originate", "meaning": "发源；产生", "pos": "v.", "sentence": "The theory originated in the 19th century."},
{"word": "ornamental", "meaning": "装饰性的", "pos": "adj.", "sentence": "The garden has many ornamental plants."},
{"word": "orphanage", "meaning": "孤儿院", "pos": "n.", "sentence": "She grew up in an orphanage."},
{"word": "orthodox", "meaning": "正统的", "pos": "adj.", "sentence": "He comes from an orthodox Jewish family."},
{"word": "oscillation", "meaning": "振荡；波动", "pos": "n.", "sentence": "The oscillation of the pendulum is regular."},
{"word": "osmosis", "meaning": "渗透", "pos": "n.", "sentence": "Plants absorb water through osmosis."},
{"word": "ostensible", "meaning": "表面上的", "pos": "adj.", "sentence": "The ostensible reason for his visit was business."},
{"word": "ourselves", "meaning": "我们自己", "pos": "pron.", "sentence": "We should take care of ourselves."},
{"word": "oust", "meaning": "驱逐；罢免", "pos": "v.", "sentence": "The CEO was ousted by the board."},
{"word": "outbreak", "meaning": "战争、病爆发", "pos": "n.", "sentence": "There was an outbreak of flu in the city."},
{"word": "outcry", "meaning": "大声疾呼", "pos": "n.", "sentence": "The decision caused a public outcry."},
{"word": "outer", "meaning": "外部的", "pos": "adj.", "sentence": "The outer layer of the skin is called the epidermis."},
{"word": "outfit", "meaning": "全套装备", "pos": "n.", "sentence": "She bought a new outfit for the party."},
{"word": "outing", "meaning": "远足；外出", "pos": "n.", "sentence": "We went on a family outing to the beach."},
{"word": "outlaw", "meaning": "歹徒；宣布非法", "pos": "n./v.", "sentence": "The government outlawed the practice."},
{"word": "outlay", "meaning": "支出；费用", "pos": "n.", "sentence": "The initial outlay was quite high."},
{"word": "outlet", "meaning": "出口；发泄途径", "pos": "n.", "sentence": "Exercise is a good outlet for stress."},
{"word": "outline", "meaning": "轮廓；大纲；概述", "pos": "n./v.", "sentence": "She outlined the main points of her argument."},
{"word": "outlying", "meaning": "偏远的", "pos": "adj.", "sentence": "The outlying villages were cut off by the flood."},
{"word": "outnumber", "meaning": "在数量上超过", "pos": "v.", "sentence": "Women outnumber men in the class."},
{"word": "outpatient", "meaning": "门诊病人", "pos": "n.", "sentence": "She was treated as an outpatient."},
{"word": "outrage", "meaning": "义愤；激怒", "pos": "n./v.", "sentence": "The scandal caused public outrage."},
{"word": "outrageous", "meaning": "残暴的；荒唐的", "pos": "adj.", "sentence": "His behavior was absolutely outrageous."},
{"word": "outright", "meaning": "彻底的；公然地", "pos": "adj./adv.", "sentence": "They rejected the proposal outright."},
{"word": "outset", "meaning": "开始", "pos": "n.", "sentence": "There were problems from the outset."},
{"word": "outsider", "meaning": "局外人", "pos": "n.", "sentence": "He felt like an outsider in the group."},
{"word": "outskirts", "meaning": "郊区", "pos": "n.", "sentence": "They live on the outskirts of the city."},
{"word": "outspoken", "meaning": "直言不讳的", "pos": "adj.", "sentence": "She is known for being outspoken."},
{"word": "outstanding", "meaning": "杰出的；未解决的", "pos": "adj.", "sentence": "He is an outstanding student."},
{"word": "outward", "meaning": "向外的；表面的", "pos": "adj.", "sentence": "She showed no outward signs of distress."},
{"word": "outweigh", "meaning": "胜过；比……更重要", "pos": "v.", "sentence": "The benefits outweigh the risks."},
{"word": "oval", "meaning": "椭圆形的", "pos": "adj.", "sentence": "The table has an oval shape."},
{"word": "ovary", "meaning": "卵巢", "pos": "n.", "sentence": "The ovaries produce eggs."},
{"word": "ovation", "meaning": "热烈欢迎；鼓掌", "pos": "n.", "sentence": "The singer received a standing ovation."},
{"word": "overall", "meaning": "总共", "pos": "adj./adv.", "sentence": "The overall result was positive."},
{"word": "overbearing", "meaning": "傲慢的；专横的", "pos": "adj.", "sentence": "His overbearing manner annoyed everyone."},
{"word": "overdue", "meaning": "过期的", "pos": "adj.", "sentence": "The library book is overdue."},
{"word": "overestimate", "meaning": "高估", "pos": "v.", "sentence": "Don't overestimate your abilities."},
{"word": "overflow", "meaning": "溢出", "pos": "v./n.", "sentence": "The river overflowed its banks."},
{"word": "overhear", "meaning": "偷听；无意中听到", "pos": "v.", "sentence": "I overheard their conversation."},
{"word": "overhaul", "meaning": "彻底检修；改革", "pos": "v./n.", "sentence": "The system needs a complete overhaul."},
{"word": "overlap", "meaning": "重叠", "pos": "v./n.", "sentence": "The two schedules overlap."},
{"word": "overload", "meaning": "超载", "pos": "v./n.", "sentence": "The system was overloaded with requests."},
{"word": "overlook", "meaning": "俯瞰；忽略", "pos": "v.", "sentence": "The hotel overlooks the ocean."},
{"word": "overpower", "meaning": "击败；使无法忍受", "pos": "v.", "sentence": "The heat overpowered him."},
{"word": "overproduction", "meaning": "生产过剩", "pos": "n.", "sentence": "Overproduction led to lower prices."},
{"word": "overrate", "meaning": "对……评价过高", "pos": "v.", "sentence": "I think the movie is overrated."},
{"word": "overrule", "meaning": "驳回；否决", "pos": "v.", "sentence": "The judge overruled the objection."},
{"word": "overseas", "meaning": "在海外", "pos": "adv.", "sentence": "He works overseas."},
{"word": "oversee", "meaning": "监督；监视", "pos": "v.", "sentence": "She oversees the daily operations."},
{"word": "overshadow", "meaning": "使失色；遮蔽", "pos": "v.", "sentence": "The scandal overshadowed his achievements."},
{"word": "oversight", "meaning": "疏忽；监督", "pos": "n.", "sentence": "The error was due to an oversight."},
{"word": "overstep", "meaning": "跨过；超越", "pos": "v.", "sentence": "He overstepped his authority."},
{"word": "overt", "meaning": "公开的", "pos": "adj.", "sentence": "There was no overt hostility between them."},
{"word": "overtake", "meaning": "追上；赶上", "pos": "v.", "sentence": "A car overtook us on the highway."},
{"word": "overthrow", "meaning": "推翻", "pos": "v.", "sentence": "The revolution overthrew the government."},
{"word": "overtime", "meaning": "超时；加班", "pos": "n./adv.", "sentence": "She works overtime every week."},
{"word": "overturn", "meaning": "推翻；翻转", "pos": "v.", "sentence": "The court overturned the previous ruling."},
{"word": "overweight", "meaning": "超重的", "pos": "adj.", "sentence": "The package is overweight."},
{"word": "overwhelm", "meaning": "压倒；使受不了", "pos": "v.", "sentence": "She was overwhelmed by the support."},
{"word": "overwhelming", "meaning": "压倒性的", "pos": "adj.", "sentence": "There was overwhelming support for the plan."},
{"word": "oxidize", "meaning": "氧化", "pos": "v.", "sentence": "Iron oxidizes when exposed to air."},
{"word": "Pacific", "meaning": "太平洋的；和平的", "pos": "adj.", "sentence": "The Pacific Ocean is the largest ocean."},
{"word": "pacify", "meaning": "使平静；安抚", "pos": "v.", "sentence": "The mother tried to pacify the crying baby."},
{"word": "packet", "meaning": "小包", "pos": "n.", "sentence": "She opened a packet of cookies."},
{"word": "pact", "meaning": "条约；协定", "pos": "n.", "sentence": "The two countries signed a trade pact."},
{"word": "pageant", "meaning": "壮观的场面；露天演出", "pos": "n.", "sentence": "The beauty pageant was held last night."},
{"word": "palatable", "meaning": "美味的；合意的", "pos": "adj.", "sentence": "The food was quite palatable."},
{"word": "pamphlet", "meaning": "小册子", "pos": "n.", "sentence": "She picked up a pamphlet about the museum."},
{"word": "panic", "meaning": "恐慌", "pos": "n./v.", "sentence": "The crowd panicked when the fire alarm went off."},
{"word": "panoramic", "meaning": "全景的", "pos": "adj.", "sentence": "The hotel offers panoramic views of the city."},
{"word": "paradigm", "meaning": "范例；模式", "pos": "n.", "sentence": "This represents a paradigm shift in thinking."},
{"word": "paradox", "meaning": "自相矛盾；悖论", "pos": "n.", "sentence": "It's a paradox that less can sometimes be more."},
{"word": "paralyze", "meaning": "使瘫痪；使无力", "pos": "v.", "sentence": "The accident paralyzed him from the waist down."},
{"word": "parameter", "meaning": "参数；界限", "pos": "n.", "sentence": "We need to define the parameters of the study."},
{"word": "paramount", "meaning": "至高无上的；首要的", "pos": "adj.", "sentence": "Safety is of paramount importance."},
{"word": "paraphrase", "meaning": "释义；意译", "pos": "v./n.", "sentence": "Can you paraphrase this sentence?"},
{"word": "parasite", "meaning": "寄生虫", "pos": "n.", "sentence": "The parasite feeds on its host."},
{"word": "parity", "meaning": "同等；平价", "pos": "n.", "sentence": "The two currencies reached parity."},
{"word": "parliament", "meaning": "议会；国会", "pos": "n.", "sentence": "The bill was passed by parliament."},
{"word": "parochial", "meaning": "狭隘的；教区的", "pos": "adj.", "sentence": "His views are rather parochial."},
{"word": "parody", "meaning": "拙劣模仿；滑稽戏", "pos": "n./v.", "sentence": "The show is a parody of politics."},
{"word": "participant", "meaning": "参与者", "pos": "n.", "sentence": "All participants received a certificate."},
];